// <auto-generated />
using System;
using Gastitis.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GastitisAPI.Migrations
{
    [DbContext(typeof(GastitisDBContext))]
    [Migration("20260914170752_AddSystemCategories")]
    partial class AddSystemCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gastitis.Domain.Entities.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SystemCode")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SystemCode")
                        .IsUnique()
                        .HasFilter("\"SystemCode\" IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "NONE",
                            SystemCode = "None"
                        },
                        new
                        {
                            Id = -2,
                            Name = "Utilities",
                            SystemCode = "Utilities"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Rent",
                            SystemCode = "Rent"
                        },
                        new
                        {
                            Id = -4,
                            Name = "Transportation",
                            SystemCode = "Transportation"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Groceries",
                            SystemCode = "Groceries"
                        },
                        new
                        {
                            Id = -6,
                            Name = "Subscriptions",
                            SystemCode = "Subscriptions"
                        },
                        new
                        {
                            Id = -7,
                            Name = "Hangouts",
                            SystemCode = "Hangouts"
                        });
                });

            modelBuilder.Entity("Gastitis.Domain.Entities.ExpenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("Gastitis.Domain.Entities.ExpenseEntity", b =>
                {
                    b.HasOne("Gastitis.Domain.Entities.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
